### ISSUE TITLE
Freecam + Excavator does not work

### ISSUE THREAD

**Issue by CrimsonMaelstrom** [GreenScripter/WurstFork#5] opened 2020-11-09 11:13 UTC
The excavator forces the camera on freecam to face a certain direction, and does not complete excavation.  The expected behavior here would be the player turning and mining out the selected area regardless and without having an effect on the freecam.

**Comment by CrimsonMaelstrom** [comment] 2020-11-09 11:19
For example, killauralegit forces the freecam to look in the angle that the player has to look to hit an entity

**Comment by GreenScripter** [comment] 2020-11-09 11:22
Duplicate of #6

**Closed** 2020-11-09 11:23 UTC
Labels: bug
